export const routes = {
  marketing: {
    home: "/",
    pricing: "/pricing",
  },
  auth: {
    login: "/sign-in",
    signup: "/sign-up",
    checkEmail: "/check-email",
    postSignIn: "/post-sign-in",
  },
  app: {
    dashboard: "/dashboard",
    tasks: "/dashboard/tasks",
    security: "/dashboard/security",
    users: "/dashboard/users",
    organizations: "/dashboard/organizations",
    subscriptions: "/dashboard/subscriptions",
    audit: "/dashboard/audit",
    billing: "/dashboard/billing",
    team: "/dashboard/team",
    roles: "/dashboard/roles",
    sessions: "/dashboard/sessions",
    settings: "/dashboard/settings",
    settingsAccount: "/dashboard/settings/account",
    settingsAuthentication: "/dashboard/settings/authentication",
    settingsActivityLog: "/dashboard/settings/activity",
    settingsTeam: "/dashboard/settings/team",
  },
} as const;
